---
title: Awesome Titles
timezone: UTC
collections:
  artists:
    title: Artists
    output: true
  people:
    title: People
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  events:
    title: events
    output: true
defaults:
- scope:
    path: ''
    type: artists
  values:
    layout: artists
    artists:
    - title: ''
      url: ''
    - title: ''
      url: ''
    - title: ''
      url: ''
    - title: ''
      url: ''
    - title: ''
      url: ''
    - title: ''
      url: ''
    - title: ''
      url: ''
    - title: ''
      url: ''
- scope:
    path: ''
    type: people
  values:
    layout: about
    image: ''
    img-alt: ''
- scope:
    path: ''
    type: events
  values:
    layout: events
    startDate: ''
    endDate: ''
    startTime: ''
    endTime: ''
    starts_at: ''
    ends_at: ''
    event_color: ''
    url: ''
url: http://www.errartistcollective.com/
baseurl: 
email: your-email@domain.com
description: Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
social:
- title: twitter
  url: http://twitter.com/jekyllrb
- title: facebook
  url: 
- title: stack-overflow
  url: http://stackoverflow.com/questions/tagged/jekyll
- title: bitbucket
  url: http://bitbucket.org/jekyll
- title: github
  url: http://github.com/jekyll
address:
- line: 3481 Melrose Place
- line: Beverly Hills, CA 90210
markdown: kramdown
permalink: pretty
sass:
  sass_dir: _sass
  style: compressed
